// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiLab.DatabaseContext;

#nullable disable

namespace WebApiLab.Migrations
{
    [DbContext(typeof(LabDbContext))]
    [Migration("20220905033229_addSeedUser")]
    partial class addSeedUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CommonClass.Models.AdminParts", b =>
                {
                    b.Property<int>("PartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartID"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(6);

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4);

                    b.Property<string>("UserModified")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.HasKey("PartID");

                    b.ToTable("Admin.Parts");

                    b.HasData(
                        new
                        {
                            PartID = 1,
                            DateCreated = new DateTime(2022, 9, 5, 10, 32, 29, 529, DateTimeKind.Local).AddTicks(9630),
                            DateModified = new DateTime(2022, 9, 5, 10, 32, 29, 529, DateTimeKind.Local).AddTicks(9641),
                            IsActive = false,
                            PartName = "Nhân viên",
                            UserCreated = "Seed",
                            UserModified = "Seed"
                        },
                        new
                        {
                            PartID = 2,
                            DateCreated = new DateTime(2022, 9, 5, 10, 32, 29, 529, DateTimeKind.Local).AddTicks(9643),
                            DateModified = new DateTime(2022, 9, 5, 10, 32, 29, 529, DateTimeKind.Local).AddTicks(9644),
                            IsActive = false,
                            PartName = "Trưởng phòng",
                            UserCreated = "Seed",
                            UserModified = "Seed"
                        },
                        new
                        {
                            PartID = 3,
                            DateCreated = new DateTime(2022, 9, 5, 10, 32, 29, 529, DateTimeKind.Local).AddTicks(9645),
                            DateModified = new DateTime(2022, 9, 5, 10, 32, 29, 529, DateTimeKind.Local).AddTicks(9645),
                            IsActive = false,
                            PartName = "Giám đốc",
                            UserCreated = "Seed",
                            UserModified = "Seed"
                        });
                });

            modelBuilder.Entity("CommonClass.Models.AdminStaff", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffID"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8);

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(12);

                    b.Property<int>("PartID")
                        .HasColumnType("int")
                        .HasColumnOrder(7);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4);

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(6);

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(10);

                    b.Property<string>("UserModified")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(11);

                    b.HasKey("StaffID");

                    b.HasIndex("PartID");

                    b.ToTable("Admin.Staffs");
                });

            modelBuilder.Entity("CommonClass.Models.AdminUser", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnOrder(9);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(6);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(12);

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasColumnOrder(2);

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(13);

                    b.Property<bool>("IsResetPassword")
                        .HasColumnType("bit")
                        .HasColumnOrder(4);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnOrder(11);

                    b.Property<string>("ProfilePictureName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(10);

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasColumnOrder(3);

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(7);

                    b.Property<string>("UserModified")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(8);

                    b.HasKey("UserName");

                    b.ToTable("Admin.Users");

                    b.HasData(
                        new
                        {
                            UserName = "Admin",
                            AccountStatus = "Normal",
                            DateCreated = new DateTime(2022, 9, 5, 10, 32, 29, 529, DateTimeKind.Local).AddTicks(9750),
                            DateModified = new DateTime(2022, 9, 5, 10, 32, 29, 529, DateTimeKind.Local).AddTicks(9751),
                            DisplayName = "Administrator",
                            HashedPassword = "j3oEIiMWevilRp5y5/mzfETFHoGnBgrj23oQuiTNtRM=",
                            Id = new Guid("fdb4a328-d81a-428c-8be7-214248a39c94"),
                            IsActive = true,
                            IsResetPassword = false,
                            PhoneNumber = "09781231234",
                            ProfilePictureName = "",
                            Salt = "kPg2GW/IblRkqFtMPrhmbw==",
                            UserCreated = "SeedSystem",
                            UserModified = "SeedSystem"
                        });
                });

            modelBuilder.Entity("CommonClass.Models.AdminStaff", b =>
                {
                    b.HasOne("CommonClass.Models.AdminParts", "Parts")
                        .WithMany()
                        .HasForeignKey("PartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
