// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiLab.DatabaseContext;

#nullable disable

namespace WebApiLab.Migrations
{
    [DbContext(typeof(LabDbContext))]
    [Migration("20220826084739_removeOldFieldAdminStaff")]
    partial class removeOldFieldAdminStaff
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CommonClass.Models.AdminParts", b =>
                {
                    b.Property<int>("PartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartID"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModified")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartID");

                    b.ToTable("Admin.Parts");

                    b.HasData(
                        new
                        {
                            PartID = 1,
                            DateCreated = new DateTime(2022, 8, 26, 15, 47, 39, 762, DateTimeKind.Local).AddTicks(8944),
                            DateModified = new DateTime(2022, 8, 26, 15, 47, 39, 762, DateTimeKind.Local).AddTicks(8958),
                            PartName = "Nhân viên",
                            UserCreated = "Seed",
                            UserModified = "Seed"
                        },
                        new
                        {
                            PartID = 2,
                            DateCreated = new DateTime(2022, 8, 26, 15, 47, 39, 762, DateTimeKind.Local).AddTicks(8960),
                            DateModified = new DateTime(2022, 8, 26, 15, 47, 39, 762, DateTimeKind.Local).AddTicks(8961),
                            PartName = "Trưởng phòng",
                            UserCreated = "Seed",
                            UserModified = "Seed"
                        },
                        new
                        {
                            PartID = 3,
                            DateCreated = new DateTime(2022, 8, 26, 15, 47, 39, 762, DateTimeKind.Local).AddTicks(8962),
                            DateModified = new DateTime(2022, 8, 26, 15, 47, 39, 762, DateTimeKind.Local).AddTicks(8962),
                            PartName = "Giám đốc",
                            UserCreated = "Seed",
                            UserModified = "Seed"
                        });
                });

            modelBuilder.Entity("CommonClass.Models.AdminStaff", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("PartID")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModified")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("PartID");

                    b.ToTable("Admin.Staffs");
                });

            modelBuilder.Entity("CommonClass.Models.AdminUser", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<bool>("IsResetPassword")
                        .HasColumnType("bit");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserCreated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModified")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("ID");

                    b.ToTable("Admin.Users");
                });

            modelBuilder.Entity("CommonClass.Models.AdminStaff", b =>
                {
                    b.HasOne("CommonClass.Models.AdminParts", "Parts")
                        .WithMany()
                        .HasForeignKey("PartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parts");
                });

            modelBuilder.Entity("CommonClass.Models.AdminUser", b =>
                {
                    b.HasOne("CommonClass.Models.AdminStaff", "Staff")
                        .WithMany()
                        .HasForeignKey("ID");

                    b.Navigation("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
